hook/extension/js/Content.js, hook/extension/js/Helper.js, hook/extension/js/StravistiX.js, hook/extension/js/modifiers/AthleteStatsModifier.js
Hi Tom,
I think it's ready to merge. It works for cycling and running.
More features will come in the future :)
regards
Taz
=> Showing progress compared to the previous years

hook/extension/js/Content.js, hook/extension/js/Helper.js, hook/extension/js/StravistiX.js, hook/extension/js/modifiers/ActivitySegmentTimeComparisonModifier.js, hook/extension/js/modifiers/AthleteStatsModifier.js
Code:
```javascript
if ($("#ytd_year_bike, #ytd_year_run").length === 0) {
setTimeout(function() {
modify();
}, 500);
return;
}
```
has to be there otherwise it won't work on a bad quality internet connection.
=> Removed dependency on UI language for year progress

hook/extension/js/Helper.js
didn't work right for small arrays.
Now works as per method 1:
https://en.wikipedia.org/wiki/Quartile
=> upper and lower Quartile code improvement

hook/extension/js/StravistiX.js, hook/extension/js/UserSettings.js, hook/extension/js/modifiers/WindyTyModifier.js, hook/extension/options/app/modules/SettingsSectionsModule.js
Allows users to change temperature and wind speed unit settings for the Windyty popup.
Added a "Units" section to Common Settings
Update call to Windyty to support wind and temp configuration
=> Add support for changing weather units

hook/extension/js/modifiers/ActivityBestSplitsModifier.js
Displays best heart rate recovery for best splits length (time/distance)
Also works the other way, best heart rate increase (time/distance)
=> Hr bestsplit

hook/extension/js/modifiers/ActivityBestSplitsModifier.js
=> Best splits : makes values comparable using a ratio

hook/extension/js/modifiers/ActivityBestSplitsModifier.js
=> Fixing wrong time/distance for best split calculation

hook/extension/js/Helper.js, hook/extension/js/modifiers/ActivityBestSplitsModifier.js, hook/extension/js/processors/ActivityProcessor.js
=> Averages should be OK now

hook/extension/js/Helper.js
=> Some percentiles are missed

hook/extension/js/modifiers/NearbySegmentsModifier.js
=> Update class matcher to what is currently set on Strava

gulpfile.js
Reduce workload on gulp watch by removing node_modules from watch list
=> To fix #241

hook/extension/js/Content.js, hook/extension/js/StravistiX.js
@thomaschampagne Fixing issue that you discovered with "fr". For, supported locales it will load messages for others it will fall back to messages in root.json.
=> Feature/pty #10 - Fix load for unsupported locales

hook/extension/js/StravistiX.js, hook/extension/js/modifiers/ActivitiesSummaryModifier.js, hook/extension/js/modifiers/AthleteStatsModifier.js, hook/extension/js/modifiers/DisplayFlyByFeedModifier.js, hook/extension/js/modifiers/SegmentRankPercentageModifier.js, hook/extension/js/modifiers/extendedActivityData/views/AscentSpeedDataView.js, hook/extension/js/modifiers/extendedActivityData/views/CyclingCadenceDataView.js, hook/extension/js/modifiers/extendedActivityData/views/CyclingGradeDataView.js, hook/extension/js/modifiers/extendedActivityData/views/PowerDataView.js, hook/extension/js/modifiers/extendedActivityData/views/SpeedDataView.js, hook/extension/locales/en-GB.json, hook/extension/locales/root.json
@thomaschampagne This completes the creation of translation keys for all titles for UI inserted in Strava using javascript.
Use en-GB locale in strava to see most strings get replaced with ########.
=> Translation complete for all titles in UI built in js - #10

hook/extension/js/StravistiX.js, hook/extension/js/modifiers/ActivitySegmentTimeComparisonModifier.js
Show additional segment information (delta to PR, segment rank) for run segments as well, not only bike ones.
=> Implement run PR/KOM handler for segments.

hook/extension/js/modifiers/ActivitySegmentTimeComparisonModifier.ts
Added EffortInfo for better type safety (and to prevent IntelliJ IDE showing unresolved variables).
=> Added EffortInfo interface

hook/extension/js/modifiers/ActivitySegmentTimeComparisonModifier.ts, hook/extension/js/modifiers/SegmentRecentEffortsHRATimeModifier.ts
Fixes the issue of power axis scale in Recent Efforts est. power graph wrong when HR data were missing for the last ride.
=> Bad axis scale for power (cycling) in Recent Efforts est. power graph

plugin/core/scripts/Background.ts, plugin/core/scripts/StravistiX.ts, plugin/core/scripts/UserSettings.ts, plugin/core/scripts/modifiers/GoalsModifier.ts, plugin/options/app/services/CommonSettingsService.ts
Restores the extended goals information and should resolve #317 by now using the Date object to load the current year.
=> Resolves Issue 317

plugin/core/scripts/Background.ts, plugin/core/scripts/StravistiX.ts, plugin/core/scripts/UserSettings.ts, plugin/core/scripts/modifiers/GoalsModifier.ts, plugin/options/app/services/CommonSettingsService.ts
Restores extendedGoals and modifies the progress bar for situations when achievements are greater than the goal value. Fixes #320
=> Fixes #320

plugin/options/app/controllers/YearProgressController.ts
Use moving_time_raw, not elapsed_time_raw
=> Fix annual summary "Time (h)" jumps

gulpfile.js, package.json
=> #394 move gulp npmInstall to npm postinstall hook

plugin/options/app/services/CommonSettingsService.ts
Incorrect description in tooltip.
=> Correct tooltip info for running activities

plugin/options/app/directives/fitnessTrend/templates/fitnessHelper.html
This pull request replaces the male pronoun ‘he’ with the gender-neutral pronoun ‘they’ in the Fitness Trend helper screen.
=> Make pronouns gender neutral: ‘He’ → ‘They’

plugin/core/scripts/interfaces/ActivityData.ts, plugin/core/scripts/modifiers/extendedActivityData/views/AbstractGradeDataView.ts, plugin/core/scripts/processors/ActivityComputer.ts, specs/processors/ActivityComputer.spec.ts
Issue #211 Find best % grade on an activity
=> Issue #211 Added avg, max, min grade for extended statistics

plugin/options/app/directives/fitnessTrend/fitnessTrendGraph.ts
I think this feature is really important (and easy to fix ;) )
=> Add Day of the Week to Tracker

plugin/common/scripts/UserSettings.ts, plugin/common/scripts/interfaces/IUserSettings.ts, plugin/core/scripts/StravistiX.ts, plugin/core/scripts/modifiers/HideFeedModifier.ts, plugin/options/app/services/CommonSettingsService.ts
For issue #472 
My first time contributing. Let me know if I left anything out.
=> add option to hide posts from activity feed

plugin/core/scripts/modifiers/ActivitySegmentTimeComparisonModifier.ts
Added percentage difference to segment time comparison for delta KOM, delta PR and delta Year PR.
=> Add Segment Percentage Difference

plugin/core/scripts/elevate.ts, plugin/core/scripts/modifiers/running-analysis-graph.modifier.ts
Fixes #438 
I played around with the naming a little bit until I thought it made sense but also fit neatly on one line.
I was going to add some tests, but it didn't look like there were any other tests for similar features. 
Should this also be hidden behind a configuration option?
=> Add link to Analysis Graph on Running activities

plugin/app/src/app/shared/dao/user-settings/user-settings.dao.ts, plugin/app/tsconfig.json, plugin/core/scripts/app-storage.ts, plugin/core/scripts/background.ts, plugin/core/scripts/content.ts, plugin/core/scripts/elevate.ts, plugin/core/scripts/installer.ts, plugin/core/tsconfig.json
=> Store all user settings data in a key instead of root storage

plugin/core/scripts/helper.ts, plugin/core/scripts/modifiers/extended-stats/abstract-extended-data.modifier.ts, plugin/core/scripts/modifiers/extended-stats/running-extended-data.modifier.ts, plugin/core/scripts/modifiers/extended-stats/views/abstract-data.view.ts, plugin/core/scripts/modifiers/extended-stats/views/running-grade-data.view.ts, plugin/core/scripts/processors/activity-computer.ts, plugin/core/specs/helper/helper.spec.ts
Having made this comment: https://github.com/thomaschampagne/elevate/pull/742/files#r251670335
I realized that I could probably address this myself. 
If there was a reason for having it several different places, I'm happy to delete/close this.
=> Centralize convertSpeedToPace into helper class

plugin/app/src/app/fitness-trend/fitness-trend-config-dialog/fitness-trend-config-dialog.component.html
=> Update the note about the configuration being stored locally

plugin/app/src/app/activities/activity-columns.namespace.ts
Intensity was never finished being added to the Activities page selection.
Fixes #962.
=> Allow Intensity to be chosen as an Activities page column
