thomaschampagne/elevate

- hook/extension/js/modifiers/RemoteLinksModifier.js
As detailed in #37 , this adds an option to export tcx files from an activity page. tcx files also contain heart rate data. The tcx export itself is provided by Strava in a method referenced in their documentation at:  https://strava.zendesk.com/entries/22555481-Exporting-your-Data-and-Bulk-Export
> Added export option for tcx files. Closes #37

- hook/extension/js/modifiers/MenuModifier.js
Setting the default navigation background-color to transparent improves the integration into the nav bar on Strava and changes this:
... to this ...
Note the nice grey underline under the button.
> Set nav button background-color to transparent

- hook/extension/options/app/modules/SettingsSectionsModule.js
Update help message for 'Move Ratio', as this option is available for  both cycling and running.
Therefore, it is better to say "during your activity" in general, instead of 'during your cycling activity'.
> Update help message for 'Move Ratio'

- hook/extension/js/modifiers/extendedActivityData/RunningExtendedActivityDataModifier.js
This PR is aiming to fix:
- The logic of when it should be displayed. From what I understood, it should be inside the `if (this.analysisData_.gradeData && this.userSettings_.displayAdvancedGradeData)`, just like the others. When it's turned on, we show it.
- The unit of 'Avg climbing pace', as shown in the screenshots below.
Before fixing:
After fixing:
> Avg climbing pace fix

- hook/extension/js/modifiers/extendedActivityData/AbstractExtendedActivityDataModifier.js
- hook/extension/js/modifiers/extendedActivityData/CyclingExtendedActivityDataModifier.js
- hook/extension/js/processors/ActivityProcessor.js
I've added median cadence and cadence standard deviation to the content summary grid (if user has opted to include cadence stats in the extended views). I (and a few of my friends) found this information useful during focused cadence training.
> Median cadence and cadence std dev added

- hook/extension/js/processors/ActivityProcessor.js
Fix for incorrect calculation of cadence variance and standard deviation. Previous version failed to calculate the sum of squared cadence measurements, resulting in always presenting 0 standard deviation.
> Cadence standard deviation fixed. 

- hook/extension/INSTALL.md
Includes a minor correction too. I think it was important to specify `node make init` here, since these are independent install instructions just like in README.
> Updating install instructions in INSTALL.md

- gulpfile.js
- hook/extension/locales/en-GB.json
- hook/extension/locales/root.json
- hook/extension/options/app/App.js
- hook/extension/options/app/controllers/MainController.js
- hook/extension/options/app/controllers/XtdZonesSettingsController.js
- hook/extension/options/app/directives/hrZones/templates/healthCustomZones.html
- hook/extension/options/app/directives/hrZones/templates/hrZone.html
- hook/extension/options/app/directives/xtdZones/templates/xtdZone.html
- hook/extension/options/app/directives/xtdZones/templates/xtdZones.html
- hook/extension/options/app/filters/TranslationFilter.js
- hook/extension/options/app/index.html
- hook/extension/options/app/views/headerNav.html
- hook/extension/options/app/views/healthSettings.html
- hook/extension/package.json
@thomaschampagne Enabled translation for Health and Zone settings pages. But, hit an obstacle with header titles. The javascript running the translation is not loaded before the headerNav is loaded so, cannot dynamically translation the strings.
Any suggestions on how to solve this are welcome?
> #10 - Translation enabled for Health settings and Zone Settings pages.

- hook/extension/css/extendedData.css
- hook/extension/js/Content.js
- hook/extension/js/Helper.js
- hook/extension/js/StravistiX.js
- hook/extension/js/UserSettings.js
- hook/extension/js/modifiers/SegmentRecentEffortsHRATimeModifier.js
- hook/extension/options/app/services/CommonSettingsService.js
Add heart rate adjusted performance into the segment Recent efforts graph - pace is adjusted for running, power for riding. The intention is to show the approximate fitness history in the segment.
Performance is adjusted based on assumption pace / power is linear to HRR, see [Tracking Fitness With the "Heart Rate-Running Speed Index"](http://www.runnersworld.com/sweat-science/tracking-fitness-with-the-heart-rate-running-speed-index). The highest HR from efforts in the segment is used as a target HR to which all other efforts are readjusted.
Only efforts with HR data are included in the graph, no graph is created unless there are at least two efforts present with HR data.
Option is added for this, by default true.
Screenshot - running:
Screenshot - bike:
> Heart rate adjusted recent efforts graph

- hook/extension/js/modifiers/SegmentRecentEffortsHRATimeModifier.ts
More robust SVG infobox insertion, not relying on dynamic #mark-selected. This should solve the issues of infobox sometimes not appearing at all, or sometimes selected mark visible over it.
> More robust SVG infobox insertion for Recent Efforts

- hook/extension/js/Helper.ts
Fixed: recent efforts running time range wrong when old efforts were missing HR data (introduced in 5f2d8c06c5131939837fe3571e4865ef812c1f08)
The helper functions `safeMin` / `safeMax` expected `undefined` values, not `null` values. Current version handles `null`, and it should handle both if needed, as `undefined == null` (see http://stackoverflow.com/a/12690122/16673).
> Fixed: recent efforts running time range wrong sometimes

- hook/extension/js/modifiers/SegmentRecentEffortsHRATimeModifier.ts
In one of my recent efforts one running effort is returning avg_watts value present. Current code decided to show watts instead of a time as a scale for heart rate adjusted data.
This looks like a Strava bug - why should running ever report watts?
I have changed it so shat watts are shown only when all efforts have avg_watts present to work around this. I did not see any failure with any of my bike or running segment I have checked.
For my record:
- the segment is https://www.strava.com/segments/12556730?filter=my_results.
- the activity is https://www.strava.com/activities/633052397
Note: the activity was fixed using [SNAP utility](http://strava-tools.raceshape.com/snap/) and uploaded again - chance is it might be causing this?
> Fixed: Recent efforts for running could rarely show watts instead of time

- hook/extension/js/modifiers/GoalsModifier.ts
This fixes the issue as described by @Langlaeufer in #285 where extended annuals goals break when certain locales are used. Specifically, those that format numbers such as 1.500,0 -- instead of the previously assumed 1,500.0.
> Deal with other number formats when parsing goals

- hook/extension/js/modifiers/GoalsModifier.ts
Follow up for #302 and this time I swear it's for realsies. 😊
Turns out Strava actually has loads of (well, at least three) different number formats. As @Langlaeufer astutely pointed out in #302, I should just strip all non-numeric characters, instead of trying to be smart. My bad. Also I got rid of the whole trying to deal with decimals. I don't think Strava actually includes them anyway -- although I wish I could be more confident in that assertion.
> Actually deal with other number formats when parsing goals

- plugin/core/scripts/modifiers/GoalsModifier.ts
Comparing dates with different units, monthsStart is taken from a Date object which gives miliseconds, start_date_local_raw is in seconds.
This prevented 2nd (3rd, 4th..) pages of activities from being loaded and meant that monthly stats for users with more than 20 activities ( 1 page of results) or with mixed activity types did not see the full total of distance travelled for the month in the progress bars.
> Corrected date comparison for seconds/miliseconds

- plugin/core/scripts/Content.ts
- plugin/core/scripts/StravistiX.ts
- plugin/core/scripts/UserSettings.ts
- plugin/core/scripts/modifiers/HideFeedModifier.ts
- plugin/options/app/services/CommonSettingsService.ts
Hi,
This PR adds the option to hide virtual rides from the activity feed (I have noticed a lot of them on my feed and I would like the ability to hide them).
It also resolves activity type resolution in the activity feed hider module. Looks like the html structure has changed from when the initial code was written which I guess would mean the minimum distance ride/run filters may not have been working, unless I have misinterpreted what the original code was doing.
This is my first typescript PR so let me know if it is not stylistically correct. I have tried to follow the established patterns in the code as closely as possible.
I think there could be room for improvement around working out whether or not the modifiers should run or not? Maybe using a strategy pattern or something? I didn't …
> adds option to hide virtual rides from activity feed

- plugin/core/scripts/modifiers/AthleteStatsModifier.ts
The hover text for the trend arrow currently states 'x undefined' instead of 'x ft'.
This commit fixes it by correcting scoping the function so it has access to the elevationUnit.
> Fixing the units on the elevation trend arrow

- plugin/core/scripts/StravistiX.ts
- plugin/core/scripts/UserSettings.ts
- plugin/core/scripts/modifiers/HideFeedModifier.ts
- plugin/options/app/services/CommonSettingsService.ts
Addressing issue #382, although based on the screenshot taken when this issue was opened Strava has since moved this section to the sidebar where it does not interfere with the activity feed.
> Issue #382 Option to hide suggested athletes on dashboard

- plugin/options/app/services/FitnessDataService.ts
Hi,
I am having a problem on the multisports fitness trend graph where those e-bike rides show up since I started using them for commute now. I don't think having them on the graph are helpful at all.
In the long run, it is probably better(?) to have an option and let user pick the sports that they don't care and exclude them. What do you think?
Thanks,
-Kyle
> Exclude EBikeRide in Multisports Fitness Trend

- plugin/core/scripts/processors/activity-computer.ts
- plugin/core/specs/processors/activity-computing/activity-computer-power.spec.ts
- plugin/core/specs/processors/activity-computing/activity-computer.spec.ts
Fix #658.
@thomaschampagne This is work in progress. Just wanted to show you what I'm thinking. Btw, is there a way to quickly recalculate the metrics without clearing all activities in the plugin? 
I also have several questions:
1. [Here](https://github.com/thomaschampagne/elevate/blob/12ba302446529c9c53def2a35b19ec967558574b/plugin/core/scripts/processors/activity-computer.ts#L659) Am I right assuming that the delta time between too samples may not be consistent? I.e., it could be of different length between different samples? I assume that that is the case for Garmin watches in Smart mode, for example.
2. What's the right way to treat non-moving samples? Should I just ignore them completely, or continue rolling window through them? If the stopped interval is long, the average will …
> Fix weighted power by using proper rolling window

- plugin/app/src/app/athlete-settings/components/dated-athlete-settings-manager/dated-athlete-settings-manager.component.html
This warning icon seemed to be the only one in the application which didn't use the warn colour.  It looked fine in yellow on the classic dark theme, but seemed out of place on most other themes (including the classic light theme).
> Fix minor grammar issue and change warning icon to warn colour

- plugin/app/package-lock.json
- plugin/app/package.json
- plugin/app/src/app/athlete-settings/components/dated-athlete-settings-manager/models/dated-athlete-settings-table.model.ts
- plugin/app/src/app/athlete-settings/components/edit-dated-athlete-settings-dialog/edit-dated-athlete-settings-dialog.component.ts
Here's a stab at fixing #705.  Hopefully there are tests around the dates that can catch if anything has broken due to incorrect date storage.
Resources:
https://blog.angular.io/taking-advantage-of-the-angular-material-datepicker-237e80fa14b3
https://material.angular.io/components/datepicker/examples
> Add MomentDateAdapter to solve shifting dates issue; fixes #705

- plugin/core/scripts/modifiers/hide-feed.modifier.ts
Though this regex is less readable than replacements chain, it is more durable.  If Strava (or another browser extension) modifies the classes on that element, this will replace any classes which don't begin with "icon-" (as well as replace icon-lg and icon-dark).
Unfortunately, the regex will still have to be updated if Strava adds new "icon-" classes.  There's also no way to account for other "icon-" classes added by other extensions, so lets hope "icon-<activityType>" comes before those others.
> Replace the chain of replacements with a single regex to do the same

- plugin/app/src/app/fitness-trend/fitness-trend-graph/fitness-trend-graph.component.html
A minor enhancement so the FitnessTrend will update on window:focus.  
I noticed that I was frequently confused/annoyed if I switched to the pinned Elevate tab and it displayed a different day (whenever I last viewed the tab) as "Today, Thursday, January 10th 2019".  This PR doesn't add much (only one line, in fact), but switching to a tab with FitnessTrend open will set today as the viewed day (like `onGraphMouseOut()`) and update the legend accordingly.
> Update FitnessTrend on window:focus, acting like onGraphMouseOut

- plugin/core/scripts/modifiers/menu.modifier.ts
It's a bit scary from a privacy perspective when an extension always requests your location. (I wonder if it has malware, is selling my location, etc..) So, I've updated the code so the global heatmap menu item only requests the location when it's clicked vs. on every load.
> Only request the user's location when global heatmap is requested

- plugin/core/scripts/modifiers/segment-recent-efforts-hratime.modifier.ts
The Beta feature "Display running estimated paces & cycling estimated powers from most painful effort on a segment (Experimental)" was broken since 5625f9bc56f6b1facfbc8e58d8be1dc487e847d0, as `safeMin`/`safeMax`  no longer worked for uninitialized values.
This is a trivial fix of the issue.
> Fix running hr

- plugin/app/src/app/fitness-trend/shared/models/day-stress.model.ts
The discrepancy in stress score values between the Fitness Trend and Activities pages is due to the use of floor() in Fitness Trend and round() in Activities. I'm sure when first creating the program there was some reasoning behind using floor() on the Fitness Trend page, but changing to round() was the easiest solution of the three:
1) Modify the stress calculation at the source (activity-computer) to output a number with no decimals (rounded, or floored) - pretty simple but I don't think the after effects (losing precision for future calculations) would be worth it.
2) Modify the Activities table namespace to write a custom detection for stress scores to floor() the values instead of round() - pretty roundabout and involved due to how the namespace and table is programmed already
3) …
> Fix stress score discrepancy

- plugin/app/src/app/activities/activity-columns.namespace.ts
I just noticed this today, and it looks to be a quick and easy fix.
> Fix #868, incorrect units for (Avg/max) HRR in Activities view

- plugin/core/scripts/processors/activity-computer.ts
activityStream was still being passed, but rejecting the 404 error for the promise would prematurely terminate the sync. Modifying the checks allowed for actual runs and manual activities to work.
Fixes #788, #897
> Fix manual activities not having RSS
